# Generated by Django 5.2.8 on 2025-12-04 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='license_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
