# Generated by Django 5.2.8 on 2025-12-20 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_driver_license_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Current latitude position', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='current_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Current longitude position', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='location_permission_granted',
            field=models.BooleanField(default=False, help_text='Has user granted location permission'),
        ),
        migrations.AddField(
            model_name='user',
            name='location_updated_at',
            field=models.DateTimeField(blank=True, help_text='When location was last updated', null=True),
        ),
    ]
