# Generated by Django 5.2.8 on 2025-12-22 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_current_latitude_user_current_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='current_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Current latitude position', max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='current_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Current longitude position', max_digits=9, null=True),
        ),
    ]
