# Generated by Django 5.2.8 on 2025-11-20 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('pickup_longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('pickup_address', models.TextField()),
                ('dropoff_latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('dropoff_longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('dropoff_address', models.TextField()),
                ('ride_type', models.CharField(choices=[('solo', 'Solo Ride'), ('shared', 'Shared Ride')], default='sole', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('picked_up', 'Picked Up'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('distance', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('fare', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('picked_up_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('passenger_rating', models.IntegerField(blank=True, null=True)),
                ('driver_rating', models.IntegerField(blank=True, null=True)),
                ('passenger_review', models.TextField(blank=True)),
                ('driver_review', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='SharedRide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('pickup_longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('dropoff_latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('dropoff_longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('fare_share', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
    ]
