# Generated by Django 5.2.8 on 2025-11-24 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='ride_type',
            field=models.CharField(choices=[('solo', 'Solo Ride'), ('shared', 'Shared Ride')], default='solo', max_length=10),
        ),
    ]
